apiVersion: apps/v1
kind: Deployment
metadata:
    name: throneteki-lobby
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: throneteki-lobby
    template:
        metadata:
            labels:
                app: throneteki-lobby
        spec:
            containers:
                - name: throneteki-lobby
                  image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
                  ports:
                      - containerPort: 80
                  env:
                      - name: NODE_CONFIG
                        valueFrom:
                            secretKeyRef:
                                name: throneteki-lobby-secret
                                key: node_config
