apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: throneteki-lobby
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    entryPoints:
        - web
        - websecure
    routes:
{{- if eq .Values.environment "production" }}
        - match: Host(`throneteki.net`) || Host(`theironthrone.net`)
          kind: Rule
          services:
              - name: throneteki-lobby
                port: 80
    tls:
        secretName: throneteki-lobby-tls
{{- else }}
        - match: Host(`{{ .Values.environment }}.throneteki.net`) || Host(`{{ .Values.environment }}.theironthrone.net`)
          kind: Rule
          services:
              - name: throneteki-lobby
                port: 80
    tls:
        secretName: throneteki-lobby-{{ .Values.environment }}-tls
{{- end }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: throneteki-lobby-cert
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    secretName: throneteki-lobby-{{ .Values.environment }}-tls
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    dnsNames:
{{- if eq .Values.environment "production" }}
        - throneteki.net
        - theironthrone.net
{{- else }}
        - {{ .Values.environment }}.throneteki.net
        - {{ .Values.environment }}.theironthrone.net
{{- end }}
