apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: game-node
  namespace: {{ .Values.namespace }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
  {{- range $i, $e := until (.Values.replicaCount | int) }}
  {{- if eq $.Values.environment "production" }}
    - match: (Host(`throneteki.net`) || Host(`theironthrone.net`)) && PathPrefix(`/node{{$i}}/socket.io`)
  {{- else }}
    - match: (Host(`{{ $.Values.environment }}.throneteki.net`) || Host(`{{ $.Values.environment }}.theironthrone.net`)) && PathPrefix(`/node{{$i}}/socket.io`)
  {{- end }}
      kind: Rule
      services:
        - name: node{{$i}}
          port: 80
  {{- end }}
