apiVersion: v1
kind: Service
metadata:
    name: node
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    clusterIP: None
    selector:
        app: game-node
    ports:
        - port: 80
          name: socketio
