apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: node
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    serviceName: node
    # prettier-ignore
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: game-node
    template:
        metadata:
            labels:
                app: game-node
            annotations:
                #prettier-ignore
                checksum/secret: {{ .Values.nodeConfig | toJson | sha256sum }}
                #prettier-ignore
                checksum/image: {{ .Values.image.tag | sha256sum }}
        spec:
            containers:
                - name: throneteki-node
                  image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  env:
                      - name: NODE_ENV
                        value: 'production'
                      - name: SERVER
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: NODE_CONFIG
                        valueFrom:
                            secretKeyRef:
                                name: throneteki-node-secret
                                key: node_config
