apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: game-node
    # prettier-ignore
    namespace: {{ .Values.namespace }}
spec:
    serviceName: game-node
    # prettier-ignore
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: game-node
    template:
        metadata:
            labels:
                app: game-node
            annotations:
                #prettier-ignore
                checksum/secret: {{ .Values.nodeConfig | toJson | sha256sum }}
        spec:
            containers:
                - name: throneteki-node
                  image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
                  ports:
                      - containerPort: 80
                  env:
                      - name: NODE_IDENTITY
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: NODE_CONFIG
                        valueFrom:
                            secretKeyRef:
                                name: throneteki-node-secret
                                key: node_config
