namespace: throneteki-development
environment: development

image:
    repository: cryogen/throneteki-lobby
    tag: latest

# Node configuration - should be passed from GitHub secrets during deployment
nodeConfig: {}

resources: {}
