replicaCount: 1
namespace: throneteki-development

image:
    repository: cryogen/throneteki-node
    tag: latest

# Deployment timestamp - injected by CI/CD to force pod updates
deployTime: '0'

# Node configuration - should be passed from GitHub secrets during deployment
nodeConfig: {}

resources: {}
