name: Deploy Game Nodes
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Select the environment
                default: Production

jobs:
    deploy:
        runs-on: self-hosted
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Deploy Game Nodes
              run: |
                  # Determine namespace
                  if [ "${{ github.event.inputs.environment }}" = "Production" ]; then
                    NAMESPACE="throneteki"
                    REPLICAS=2
                  else
                    ENV=$(echo "${{ github.event.inputs.environment }}" | tr '[:upper:]' '[:lower:]')
                    NAMESPACE="throneteki-$ENV"
                    REPLICAS=1
                  fi

                  echo "Deploying to namespace: $NAMESPACE with $REPLICAS replicas"

                  helm upgrade --install game-node ./infrastructure/node \
                    --set namespace=$NAMESPACE \
                    --set replicaCount=$REPLICAS \
                    -n $NAMESPACE
