name: Deploy Game Nodes
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Select the environment
                default: Production

jobs:
    deploy:
        runs-on: self-hosted
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Deploy Game Nodes
              run: |
                  # Determine namespace and replicas based on environment
                  ENV=$(echo "${{ github.event.inputs.environment }}" | tr '[:upper:]' '[:lower:]')
                  
                  if [ "${{ github.event.inputs.environment }}" = "Production" ]; then
                    NAMESPACE="throneteki"
                    REPLICAS=2
                  else
                    NAMESPACE="throneteki-$ENV"
                    REPLICAS=1
                  fi

                  echo "Deploying to namespace: $NAMESPACE with $REPLICAS replicas for environment: $ENV"

                  # Create values file with secrets
                  cat > /tmp/node-secrets.yaml <<EOF
                  nodeConfig:
                    env: "${{ vars.NODE_ENV || 'production' }}"
                    instance:
                      type: "$ENV"
                    sentryDsn: "${{ secrets.SENTRY_DSN }}"
                    dbPath: "${{ secrets.DB_PATH }}"
                    redisPrefix: "$ENV"
                    redisUrl: "${{ secrets.REDIS_URL }}"
                    secret: "${{ secrets.APP_SECRET }}"
                    hmacSecret: "${{ secrets.HMAC_SECRET }}"
                    lobbyUrl: "${{ vars.LOBBY_URL }}"
                  EOF

                  helm upgrade --install game-node ./infrastructure/node \
                    --set namespace=$NAMESPACE \
                    --set replicaCount=$REPLICAS \
                    --set environment=$ENV \
                    -f /tmp/node-secrets.yaml \
                    -n $NAMESPACE

                  # Clean up secrets file
                  rm /tmp/node-secrets.yaml