name: Deploy Lobby
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Select the environment
                default: Production

jobs:
    deploy:
        runs-on: self-hosted
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Apply Lobby manifests
              run: |
                  # Determine namespace
                  if [ "${{ github.event.inputs.environment }}" = "Production" ]; then
                    NAMESPACE="throneteki"
                  else
                    NAMESPACE="throneteki-$(echo "${{ github.event.inputs.environment }}" | tr '[:upper:]' '[:lower:]')"
                  fi

                  echo "Deploying to namespace: $NAMESPACE"

                  # Apply manifests
                  kubectl apply -f infrastructure/${{ github.event.inputs.environment | lower }}/lobby.yaml -n $NAMESPACE
                  kubectl apply -f infrastructure/${{ github.event.inputs.environment | lower }}/ingress.yaml -n $NAMESPACE

                  # Verify rollout
                  kubectl rollout status deployment/throneteki-lobby -n $NAMESPACE
