name: Deploy Lobby
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Select the environment
                default: Production

jobs:
    deploy:
        runs-on: self-hosted
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Deploy Lobby
              run: |
                  # Determine namespace and environment based on environment
                  ENV=$(echo "${{ github.event.inputs.environment }}" | tr '[:upper:]' '[:lower:]')

                  if [ "${{ github.event.inputs.environment }}" = "Production" ]; then
                    NAMESPACE="throneteki"
                    APP_NAME="The Iron Throne"
                    ENV_SUBDOMAIN="production"
                  elif [ "${{ github.event.inputs.environment }}" = "Development" ]; then
                    NAMESPACE="throneteki-development"
                    APP_NAME="The Iron Throne"
                    ENV_SUBDOMAIN="dev"
                  elif [ "${{ github.event.inputs.environment }}" = "Playtesting" ]; then
                    NAMESPACE="throneteki-playtesting"
                    APP_NAME="The Iron Throne Playtesting"
                    ENV_SUBDOMAIN="playtesting"
                  else
                    NAMESPACE="throneteki-$ENV"
                    APP_NAME="The Iron Throne"
                    ENV_SUBDOMAIN="$ENV"
                  fi

                  echo "Deploying lobby to namespace: $NAMESPACE for environment: $ENV_SUBDOMAIN"

                  # Generate a unique deployment timestamp to force pod updates
                  DEPLOY_TIME=$(date +%s)
                  echo "Deployment timestamp: $DEPLOY_TIME"

                  # Create values file with secrets
                  cat > /tmp/lobby-secrets.yaml <<EOF
                  nodeConfig:
                    env: "'production'"
                    instance:
                      type: "$ENV"
                      reviewFormId: "${{ secrets.REVIEWS_FORM_ID }}"
                    appName: "$APP_NAME"
                    sentryDsn: "${{ secrets.SENTRY_DSN }}"
                    captchaKey: "${{ secrets.CAPTCHA_KEY }}"
                    minLobbyChatTime: 3600
                    dbPath: "${{ secrets.DB_PATH }}"
                    cookieLifetime: 604800000
                    redisPrefix: "$ENV"
                    redisUrl: "${{ secrets.REDIS_URL }}"
                    secret: "${{ secrets.SECRET }}"
                    emailKey: "${{ secrets.EMAIL_KEY }}"
                    emailBlockKey: "${{ secrets.EMAIL_BLOCK_KEY }}"
                    port: 80
                    hmacSecret: "${{ secrets.HMAC_SECRET }}"
                    requireActivation: false
                    patreonCallbackUrl: "${{ secrets.PATREON_CALLBACK_URL }}"
                    patreonClientId: "${{ secrets.PATREON_CLIENT_ID }}"
                    patreonSecret: "${{ secrets.PATREON_SECRET }}"
                  EOF

                  helm upgrade --install throneteki-lobby ./infrastructure/lobby \
                    --set namespace=$NAMESPACE \
                    --set environment=$ENV_SUBDOMAIN \
                    --set deployTime=$DEPLOY_TIME \
                    -f /tmp/lobby-secrets.yaml \
                    -n $NAMESPACE

                  # Clean up secrets file
                  rm /tmp/lobby-secrets.yaml

                  # Verify rollout
                  kubectl rollout status deployment/throneteki-lobby -n $NAMESPACE
