name: Deploy Lobby
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Select the environment
                default: Production
jobs:
    deploy:
        runs-on: self-hosted
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Apply dev Lobby manifests
              run: |
                  kubectl apply -f infrastructure/dev/lobby.yaml -n throneteki-dev
                  kubectl apply -f infrastructure/dev/ingress.yaml -n throneteki-dev

            - name: Verify rollout
              run: |
                  kubectl rollout status deployment/throneteki-lobby -n throneteki-dev
