name: Deploy Game Nodes
on:
    workflow_dispatch:
        inputs:
            environment:
                type: environment
                description: Select the environment
                default: Production

jobs:
    deploy:
        runs-on: self-hosted
        environment: ${{ inputs.environment }}
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Deploy Game Nodes
              run: |
                  # Determine namespace and replicas based on environment
                  ENV=$(echo "${{ github.event.inputs.environment }}" | tr '[:upper:]' '[:lower:]')

                  if [ "${{ github.event.inputs.environment }}" = "Production" ]; then
                    NAMESPACE="throneteki"
                    REPLICAS=2
                    ENV_SUBDOMAIN="production"
                  elif [ "${{ github.event.inputs.environment }}" = "Development" ]; then
                    NAMESPACE="throneteki-development"
                    REPLICAS=1
                    ENV_SUBDOMAIN="dev"
                  elif [ "${{ github.event.inputs.environment }}" = "Playtesting" ]; then
                    NAMESPACE="throneteki-playtesting"
                    REPLICAS=1
                    ENV_SUBDOMAIN="playtesting"
                  else
                    NAMESPACE="throneteki-$ENV"
                    REPLICAS=1
                    ENV_SUBDOMAIN="$ENV"
                  fi

                  echo "Deploying to namespace: $NAMESPACE with $REPLICAS replicas for environment: $ENV_SUBDOMAIN"

                  # Generate a unique deployment timestamp to force pod updates
                  DEPLOY_TIME=$(date +%s)
                  echo "Deployment timestamp: $DEPLOY_TIME"

                  # Create values file with secrets
                  cat > /tmp/node-secrets.yaml <<EOF
                  nodeConfig:
                    env: "${{ vars.NODE_ENV || 'production' }}"
                    instance:
                      type: "$ENV"
                    sentryDsn: "${{ secrets.SENTRY_DSN }}"
                    dbPath: "${{ secrets.DB_PATH }}"
                    redisPrefix: "$ENV"
                    redisUrl: "${{ secrets.REDIS_URL }}"
                    secret: "${{ secrets.SECRET }}"
                    hmacSecret: "${{ secrets.HMAC_SECRET }}"
                    lobbyUrl: "${{ vars.LOBBY_URL }}"
                    socketioPort: 80
                  EOF

                  helm upgrade --install game-node ./infrastructure/node \
                    --set namespace=$NAMESPACE \
                    --set replicaCount=$REPLICAS \
                    --set environment=$ENV_SUBDOMAIN \
                    --set deployTime=$DEPLOY_TIME \
                    -f /tmp/node-secrets.yaml \
                    -n $NAMESPACE

                  # Clean up secrets file
                  rm /tmp/node-secrets.yaml

                  # Wait for rollout to complete
                  kubectl rollout status statefulset/node -n $NAMESPACE --timeout=10m
